mode: "debug"
logPath: "c:/workspace/demogolang/logrus.log"
tempPath: "./temp"
mkcert:
  cert: "c:/workspace/mkcert/localhost+2.pem"
  key: "c:/workspace/mkcert/localhost+2-key.pem"
connection:
  pool:
    maxLifetime: 1
    maxOpenConns: 1
    maxIdleConns: 1
  sqlserver:
    server: "localhost"
    port: 1433
    database: "mssql"
    username: "sa"
    password: "1qaz!QAZ"
  postgres:
    host: "localhost"
    port: 5432
    database: "postgres"
    username: "postgres"
    password: "1qaz!QAZ"
    